### ISSUE TITLE
Error: Bad state: No element [Flutter web]

### ISSUE THREAD

**Issue by jonasbeyer** [flutterchina/dio#1008]
The [retrofit.dart](https://github.com/trevorwang/retrofit.dart/) generator builds this method for a DELETE request (`@DELETE("projects/{projectId}")`), but it's only working on Android and iOS. If the method is called in the browser, an exception is thrown and the request is never sent to the server.

 I think it's related to the empty data map. If I remove the data parameter, the request is sent to the server.

```
  @override
  Future<void> deleteProject(projectId) async {
    ArgumentError.checkNotNull(projectId, 'projectId');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    await _dio.request<void>('projects/$projectId',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'DELETE',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl,
        ),
        // data: _data --> has to be removed
   );
    return null;
  }
```

```
Error: Bad state: No element
    at Object.throw_ [as throw] (http://localhost:27325/dart_sdk.js:4328:11)
    at http://localhost:27325/dart_sdk.js:18343:27
    at _RootZone.runGuarded (http://localhost:27325/dart_sdk.js:37356:11)
    at sendDone (http://localhost:27325/dart_sdk.js:31019:24)
    at _SinkTransformerStreamSubscription.new.[_sendDone] (http://localhost:27325/dart_sdk.js:31029:11)
    at _SinkTransformerStreamSubscription.new.[_close] (http://localhost:27325/dart_sdk.js:30941:26)
    at _SinkTransformerStreamSubscription.new.[_close] (http://localhost:27325/dart_sdk.js:35744:22)
    at _EventSinkWrapper.new.close (http://localhost:27325/dart_sdk.js:35684:29)
    at _HandlerEventSink.new.close (http://localhost:27325/dart_sdk.js:35968:16)
    at _SinkTransformerStreamSubscription.new.[_handleDone] (http://localhost:27325/dart_sdk.js:35798:34)
    at _RootZone.runGuarded (http://localhost:27325/dart_sdk.js:37356:11)
    at sendDone (http://localhost:27325/dart_sdk.js:31019:24)
    at _BufferingStreamSubscription.new.[_sendDone] (http://localhost:27325/dart_sdk.js:31029:11)
    at _IterablePendingEvents.new.handleNext (http://localhost:27325/dart_sdk.js:34276:32)
    at async._AsyncCallbackEntry.new.callback (http://localhost:27325/dart_sdk.js:34210:16)
    at Object._microtaskLoop (http://localhost:27325/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:27325/dart_sdk.js:37714:13)
    at http://localhost:27325/dart_sdk.js:33226:9
```

**Comment by rezaei99** [comment]
Any update on this? I encountered the same problem.
