### ISSUE TITLE
Upload: DioErrorType.DEFAULT on audio files

### ISSUE THREAD

**Issue by marcoberetta96** [flutterchina/dio#1057]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | Channel stable, 1.22.6                              |      |
| Dio Version                    | 3.0.10                                  |      |
| Android Studio / Xcode Version | Android Studio 4.1.2              |      |
| Repro rate                     | all the time   |      |

### Issue Description and Steps
When trying to upload an audio file (.aac), the following error happens:
```
I/flutter ( 5187): DioError [DioErrorType.DEFAULT]: type '_StreamHandlerTransformer<List<int>, Uint8List>' is not a subtype of type 'StreamTransformer<Uint8List, Uint8List>' of 'streamTransformer'
I/flutter ( 5187): #0      Stream.transform (dart:async/stream.dart)
I/flutter ( 5187): #1      DioMixin._transformData (package:dio/src/dio.dart:1039:18)
I/flutter ( 5187): #2      DioMixin._dispatchRequest (package:dio/src/dio.dart:921:26)
I/flutter ( 5187): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
I/flutter ( 5187): #4      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
I/flutter ( 5187): #5      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
I/flutter ( 5187): #6      new Future.<anonymous closure> (dart:async/future.dart:175:37)
I/flutter ( 5187): #7      _rootRun (dart:async/zone.dart:1182:47)
I/flutter ( 5187): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 5187): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 5187): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
I/flutter ( 5187): #11 
```
Here the interested piece of code.
```
        await Dio().put(
          presignedUrl,
          data: file.openRead(),
          options: Options(
            contentType: lookupMimeType(file.path),
            headers: {
              "Content-Length": file.lengthSync(),
              'x-amz-acl': 'public-read',
            },
          ),
        );
```

**Comment by marcoberetta96** [comment]
I checked the runtime type of `file.openRead()` when `file` is a `aac` format `File`.

It actually is `_BoundSinkStream<dynamic, Uint8List>` and I think this is the problem.

How can I solve it?
