### ISSUE TITLE
Bad state: Stream has already been listened to

### ISSUE THREAD

**Issue by jefrisingh** [flutterchina/dio#1070]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / web                           |      |
| Platform Version               | chrome                           |      |
| Dio Version                    | ^4.0.0-beta4                                  |      |
| Android Studio / Xcode Version |Android Studio 4.1.2              |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | Yes with my url            |      |
| Demo project link              | |      |

### Issue Description and Steps

When I call dio.post() I got bellow error

`Error: Bad state: Stream has already been listened to.
    at Object.throw_ [as throw] (http://localhost:41111/dart_sdk.js:5347:11)
    at _GeneratedStreamImpl.new.[_createSubscription] (http://localhost:41111/dart_sdk.js:35789:49)
    at _GeneratedStreamImpl.new.listen (http://localhost:41111/dart_sdk.js:32219:53)
    at new _SinkTransformerStreamSubscription.new (http://localhost:41111/dart_sdk.js:37465:36)
    at _BoundSinkStream.new.listen (http://localhost:41111/dart_sdk.js:37549:28)
    at _BoundSinkStream.new.reduce (http://localhost:41111/dart_sdk.js:19618:33)
    at http://localhost:41111/packages/dio/src/interceptors/log.dart.lib.js:686:27`

**Comment by kasim1011** [comment]
facing same issue with `dio: ^4.0.0-beta5`

`Error: Bad state: Stream has already been listened to.
    at Object.throw_ [as throw] (http://localhost:49980/dart_sdk.js:5032:11)
    at _GeneratedStreamImpl.new.[_createSubscription] (http://localhost:49980/dart_sdk.js:34036:38)
    at _GeneratedStreamImpl.new.listen (http://localhost:49980/dart_sdk.js:30617:53)
    at new _SinkTransformerStreamSubscription.new (http://localhost:49980/dart_sdk.js:35635:36)
    at _BoundSinkStream.new.listen (http://localhost:49980/dart_sdk.js:35716:28)
    at _BoundSinkStream.new.reduce (http://localhost:49980/dart_sdk.js:18757:33)
    at http://localhost:49980/packages/dio/src/adapters/browser_adapter.dart.lib.js:133:27
    at _RootZone.runUnary (http://localhost:49980/dart_sdk.js:37081:59)
    at _FutureListener.then.handleValue (http://localhost:49980/dart_sdk.js:32337:29)
    at handleValueCallback (http://localhost:49980/dart_sdk.js:32864:49)
    at Function._propagateToListeners (http://localhost:49980/dart_sdk.js:32902:17)
    at _Future.new.[_complete] (http://localhost:49980/dart_sdk.js:32742:25)
    at Object._cancelAndValue (http://localhost:49980/dart_sdk.js:37460:24)
    at http://localhost:49980/dart_sdk.js:18903:17
    at _RootZone.runUnaryGuarded (http://localhost:49980/dart_sdk.js:37018:11)
    at _SinkTransformerStreamSubscription.new.[_sendData] (http://localhost:49980/dart_sdk.js:30952:22)
    at _SinkTransformerStreamSubscription.new.[_add] (http://localhost:49980/dart_sdk.js:30901:26)
    at _SinkTransformerStreamSubscription.new.[_add] (http://localhost:49980/dart_sdk.js:35555:20)
    at _EventSinkWrapper.new.add (http://localhost:49980/dart_sdk.js:35504:27)
    at http://localhost:49980/packages/dio/src/dio_mixin.dart.lib.js:565:22
    at _HandlerEventSink.new.add (http://localhost:49980/dart_sdk.js:35754:11)
    at _SinkTransformerStreamSubscription.new.[_handleData] (http://localhost:49980/dart_sdk.js:35590:34)
    at _RootZone.runUnaryGuarded (http://localhost:49980/dart_sdk.js:37018:11)
    at _BufferingStreamSubscription.new.[_sendData] (http://localhost:49980/dart_sdk.js:30952:22)
    at _IterablePendingEvents.new.handleNext (http://localhost:49980/dart_sdk.js:34151:32)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49980/dart_sdk.js:34089:16)
    at Object._microtaskLoop (http://localhost:49980/dart_sdk.js:37333:13)
    at _startMicrotaskLoop (http://localhost:49980/dart_sdk.js:37339:13)
    at http://localhost:49980/dart_sdk.js:33110:9
`

**Comment by jefrisingh** [comment]
dio: ^3.0.10
With this version everything is working fine

**Comment by wendux** [comment]
It is fix at 4.0.0-beta6 .

**Comment by kasim1011** [comment]
tried with `dio: ^4.0.0-beta6`

still facing the issue:
`
Error: Bad state: Stream has already been listened to.
    at Object.throw_ [as throw] (http://localhost:52365/dart_sdk.js:5032:11)
    at _GeneratedStreamImpl.new.[_createSubscription] (http://localhost:52365/dart_sdk.js:34036:38)
    at _GeneratedStreamImpl.new.listen (http://localhost:52365/dart_sdk.js:30617:53)
    at new _SinkTransformerStreamSubscription.new (http://localhost:52365/dart_sdk.js:35635:36)
    at _BoundSinkStream.new.listen (http://localhost:52365/dart_sdk.js:35716:28)
    at _BoundSinkStream.new.reduce (http://localhost:52365/dart_sdk.js:18757:33)
    at http://localhost:52365/packages/dio/src/adapters/browser_adapter.dart.lib.js:133:27
    at _RootZone.runUnary (http://localhost:52365/dart_sdk.js:37081:59)
    at _FutureListener.then.handleValue (http://localhost:52365/dart_sdk.js:32337:29)
    at handleValueCallback (http://localhost:52365/dart_sdk.js:32864:49)
    at Function._propagateToListeners (http://localhost:52365/dart_sdk.js:32902:17)
    at _Future.new.[_complete] (http://localhost:52365/dart_sdk.js:32742:25)
    at Object._cancelAndValue (http://localhost:52365/dart_sdk.js:37460:24)
    at http://localhost:52365/dart_sdk.js:18903:17
    at _RootZone.runUnaryGuarded (http://localhost:52365/dart_sdk.js:37018:11)
    at _SinkTransformerStreamSubscription.new.[_sendData] (http://localhost:52365/dart_sdk.js:30952:22)
    at _SinkTransformerStreamSubscription.new.[_add] (http://localhost:52365/dart_sdk.js:30901:26)
    at _SinkTransformerStreamSubscription.new.[_add] (http://localhost:52365/dart_sdk.js:35555:20)
    at _EventSinkWrapper.new.add (http://localhost:52365/dart_sdk.js:35504:27)
    at http://localhost:52365/packages/dio/src/dio_mixin.dart.lib.js:565:22
    at _HandlerEventSink.new.add (http://localhost:52365/dart_sdk.js:35754:11)
    at _SinkTransformerStreamSubscription.new.[_handleData] (http://localhost:52365/dart_sdk.js:35590:34)
    at _RootZone.runUnaryGuarded (http://localhost:52365/dart_sdk.js:37018:11)
    at _BufferingStreamSubscription.new.[_sendData] (http://localhost:52365/dart_sdk.js:30952:22)
    at _IterablePendingEvents.new.handleNext (http://localhost:52365/dart_sdk.js:34151:32)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52365/dart_sdk.js:34089:16)
    at Object._microtaskLoop (http://localhost:52365/dart_sdk.js:37333:13)
    at _startMicrotaskLoop (http://localhost:52365/dart_sdk.js:37339:13)
    at http://localhost:52365/dart_sdk.js:33110:9

`

**Comment by jefrisingh** [comment]
> It is fix at 4.0.0-beta6 .

Yes it's fixed with this release :smile:

**Comment by rohan20** [comment]
This is probably a newbie question, but where do you see version `4.0.0-beta6`? I see `3.0.10 ` as the last release tag.

**Comment by jefrisingh** [comment]
Go to https://pub.dev/packages/dio/versions/4.0.0-beta6/install

**Comment by rohan20** [comment]
@jefrisingh Maybe I wasn't clear. My question was: How does a non maintainer of this project even know that a pre release version such as `4.0.0-beta6` exists? I couldn't see this mentioned anywhere.

**Comment by jefrisingh** [comment]
@rohan20 It's in pub.dev site man, any one can see the pre release as long as the maintainer of the project updated there

**Comment by rohan20** [comment]
@jefrisingh Thank you, finally saw it. It wasn't straightforward to find :) I'll leave this screenshot here for someone who has the same question in the future:

![image](https://user-images.githubusercontent.com/8232573/110493301-e5c0f080-80f2-11eb-8465-e0344dbfc484.png)
