### ISSUE TITLE
download again after cancel 

### ISSUE THREAD

**Issue by hatemragab** [flutterchina/dio#1080]
i have problem when cancel download file then download it again 

```
I/flutter (12059): Error is DioError [DioErrorType.CANCEL]: User cancel !
E/flutter (12059): [ERROR:flutter/shell/common/shell.cc(242)] Dart Unhandled Exception: Bad state: Future already completed, stack trace: #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
E/flutter (12059): #1      _NativeSocket.tryConnectToResolvedAddresses.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:847:16)
E/flutter (12059): #2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1214:14)
E/flutter (12059): #3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1221:12)
E/flutter (12059): #4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1242:11)
E/flutter (12059): #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (12059): 
```

although I create new instance for each request 

```
class CustomDio {
  final Dio _dio = Dio();

  Future<Either<ServerError, dynamic>> download(String path,
      {Map<String, String> body,
        void sendProgress(int received,int total),
        String saveDir,
        CancelToken cancelToken}) async {
    try {
      await _dio.download(path, saveDir,
          cancelToken: cancelToken, onReceiveProgress: sendProgress);
      _dio.close();
      return Right("File Downloaded!");
      // ignore: avoid_catches_without_on_clauses
    } catch (err) {
      //    print("Error is $err");
      _dio.close(force: true);
      return Left(ServerError(data: getDioStringError(err)));
    }
  }
```

**Comment by hatemragab** [comment]
@wprater  @falkorichter  @trevorwang
