### ISSUE TITLE
Dio().post is error but Dio().get isn't error (DioError [DioErrorType.response]: XMLHttpRequest error.)

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutterchina/dio#1118]
Dio method get don't error.
var response = await Dio().get( 'get.php?username=username&password=password');
              
But it's an error when I use the Dio method post. 
var response = await Dio().post('post.php', data: {"username": "username", "password": "password"} );

Error: DioError [DioErrorType.response]: XMLHttpRequest error.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28   get current
packages/dio/src/dio_mixin.dart 819:20                                                                            assureDioError
packages/dio/src/dio_mixin.dart 678:13                                                                            _dispatchRequest
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1617:54                                 runBinary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 166:20                           handleError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 716:46                           handleError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 737:13                           _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 547:5                            [_completeError]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 603:7                            callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15  <fn>

    at Object.throw_ [as throw] (http://localhost:60929/dart_sdk.js:5334:11)
    at http://localhost:60929/packages/dio/src/interceptors/log.dart.lib.js:1399:21
    at _RootZone.runBinary (http://localhost:60929/dart_sdk.js:38894:58)
    at _FutureListener.catchError.handleError (http://localhost:60929/dart_sdk.js:33887:48)
    at handleError (http://localhost:60929/dart_sdk.js:34451:51)
    at Function._propagateToListeners (http://localhost:60929/dart_sdk.js:34477:17)
    at _Future.new.[_completeError] (http://localhost:60929/dart_sdk.js:34323:23)
    at _SyncCompleter.new.[_completeError] (http://localhost:60929/dart_sdk.js:33806:36)
    at _SyncCompleter.new.completeError (http://localhost:60929/dart_sdk.js:33729:29)
    at onError (http://localhost:60929/dart_sdk.js:33574:60)
    at _RootZone.runBinary (http://localhost:60929/dart_sdk.js:38894:58)
    at _FutureListener.then.handleError (http://localhost:60929/dart_sdk.js:33887:48)
    at handleError (http://localhost:60929/dart_sdk.js:34451:51)
    at Function._propagateToListeners (http://localhost:60929/dart_sdk.js:34477:17)
    at _Future.new.[_completeError] (http://localhost:60929/dart_sdk.js:34323:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60929/dart_sdk.js:34362:31)
    at Object._microtaskLoop (http://localhost:60929/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:60929/dart_sdk.js:39182:13)
    at http://localhost:60929/dart_sdk.js:34689:9

Help, please.

**Comment by SittiphanSittisak** [comment]
Now, I am using HTTP. However, I want to fix this. Maybe I will use Dio in the future.

**Comment by ijunc2** [comment]
I have same error.

**Comment by fede1295** [comment]
same issue do you want to fix it or not?!

**Comment by saswatsaubhagya** [comment]
same issue

**Comment by w3ggy** [comment]
Any updates?
