### ISSUE TITLE
七牛云上传失败

### ISSUE THREAD

**Issue by fengqiangboy** [flutterchina/dio#124]
七牛云上传总是失败，设置charles 为代理就可以成功，取消代理就会失败

## Steps to Reproduce

```
// 创建七牛云dio
Dio qiniuDio = Dio(
    Options(baseUrl: "https://up-z2.qbox.me"),
  );

var formData = FormData.from(
      {
        "token": token,
        "file": UploadFileInfo(file, “file.png”),
      },
    );

var response =qiniuDio.post("/", data: formData);
```

## Logs
HttpException: Connection closed before full header was received, uri = https://up-z2.qbox.me/

```
#0      _StringBase.+ (dart:core/runtime/libstring_patch.dart:251:57)
#1      Api.onError (package:bbq_ec/api/api.dart:109:60)
#2      Dio._onError (package:dio/src/dio.dart:549:34)
#3      Dio._makeRequest.<anonymous closure> (package:dio/src/dio.dart:449:28)
#4      Dio._checkIfNeedEnqueue (package:dio/src/dio.dart:587:22)
#5      Dio._makeRequest (package:dio/src/dio.dart:444:38)
<asynchronous suspension>
#6      Dio._request.<anonymous closure> (package:dio/src/dio.dart:342:16)
#7      Dio._checkIfNeedEnqueue (package:dio/src/dio.dart:587:22)
#8      Dio._request (package:dio/src/dio.dart:302:34)
<asynchronous suspension>
#9      Dio.request (package:dio/src/dio.dart:282:12)
<asynchronous suspension>
#10     Dio.post (package:dio/src/dio.dart:78:12)
#11     QiniuDao.qiniuUpload (package:bbq_ec/dao/qiniu_dao.dart:26:48)
<asynchronous suspension>
#12     MinePageContentState._setAvatar (package:bbq_ec/page/mine/mine_page.dart:234:32)
<asynchronous suspension>
#13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#14     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#15     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#19     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
#20     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
#21     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
#22     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
#23     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
#24     _invoke1 (dart:ui/hooks.dart:168:13)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

**Comment by wendux** [comment]
会不会是dart中这个域名访问不了？

**Comment by fengqiangboy** [comment]
不翻墙连接google提示的错误不是这个
是

```
SocketException: OS Error: Connection timed out, errno = 110, address = www.google.com, port = 38782
```

**Comment by wendux** [comment]
是不是上传的姿势不对，貌似是服务端关闭的，可以看看是否是七牛鉴权认证的问题

**Comment by fengqiangboy** [comment]
应该不会，应该我设置代理之后就可以，而且是电脑开的本地代理~没有翻墙的

**Comment by wendux** [comment]
没有token， 我这测不了，你可以升级到最新版本重试一下，如果还是不行，你可以下个断点跟一下，看看到底哪里有问题，也可以加我我帮你调

**Comment by fengqiangboy** [comment]
> 没有token， 我这测不了，你可以升级到最新版本重试一下，如果还是不行，你可以下个断点跟一下，看看到底哪里有问题，也可以加我我帮你调

**Comment by fengqiangboy** [comment]
> 没有token， 我这测不了，你可以升级到最新版本重试一下，如果还是不行，你可以下个断点跟一下，看看到底哪里有问题，也可以加我我帮你调

好的，谢谢啦，我再试试看能不能解决，尽量写个demo出来~

**Comment by wendux** [comment]
可以升级到最新版本，可以抓包验证一下数据是否符合期望，如确认是dio问题，再重新打开。

**Comment by fengqiangboy** [comment]
连接4G网络可以正常了~
