### ISSUE TITLE
Error: DioError [DioErrorType.response]: XMLHttpRequest error.

### ISSUE THREAD

**Issue by s2yed** [flutterchina/dio#1265]
packages/dio/src/interceptors/log.dart.lib.js 1400:191  assureDioError
packages/dio/src/interceptors/log.dart.lib.js 1282:43   _dispatchRequest
dart:sdk_internal 37408:38                              <fn>
dart:sdk_internal 37278:59                              runBinary
dart:sdk_internal 32540:48                              handleError
dart:sdk_internal 33073:51                              handleError
dart:sdk_internal 33099:17                              _propagateToListeners
dart:sdk_internal 32949:23                              [_completeError]
dart:sdk_internal 32985:31                              callback
dart:sdk_internal 37526:13                              _microtaskLoop
dart:sdk_internal 37532:13                              _startMicrotaskLoop
dart:sdk_internal 33303:9                               <fn>

    at Object.throw_ [as throw] (http://localhost:59025/web/dart_sdk.js:5041:11)
    at http://localhost:59025/web/packages/dio/src/interceptors/log.dart.lib.js:1243:21
    at _RootZone.runBinary (http://localhost:59025/web/dart_sdk.js:37278:59)
    at _FutureListener.catchError.handleError (http://localhost:59025/web/dart_sdk.js:32540:48)
    at handleError (http://localhost:59025/web/dart_sdk.js:33073:51)
    at Function._propagateToListeners (http://localhost:59025/web/dart_sdk.js:33099:17)
    at _Future.new.[_completeError] (http://localhost:59025/web/dart_sdk.js:32949:23)
    at _SyncCompleter.new.[_completeError] (http://localhost:59025/web/dart_sdk.js:32461:36)
    at _SyncCompleter.new.completeError (http://localhost:59025/web/dart_sdk.js:32388:29)
    at onError (http://localhost:59025/web/dart_sdk.js:32239:49)
    at _RootZone.runBinary (http://localhost:59025/web/dart_sdk.js:37278:59)
    at _FutureListener.then.handleError (http://localhost:59025/web/dart_sdk.js:32540:48)
    at handleError (http://localhost:59025/web/dart_sdk.js:33073:51)
    at Function._propagateToListeners (http://localhost:59025/web/dart_sdk.js:33099:17)
    at _Future.new.[_completeError] (http://localhost:59025/web/dart_sdk.js:32949:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59025/web/dart_sdk.js:32985:31)
    at Object._microtaskLoop (http://localhost:59025/web/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:59025/web/dart_sdk.js:37532:13)
    at http://localhost:59025/web/dart_sdk.js:33303:9

**Comment by jgoyvaerts** [comment]
Can you catch the dioerror and see what the stack trace is?

**Comment by GoogleJ** [comment]
Check CORS. Works for me.
