### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.other]: type '_StreamHandlerTransformer<List<int>, Uint8List>' is not a subtype of type 'StreamTransformer<Uint8List, Uint8List>' of 'streamTransformer'

### ISSUE THREAD

**Issue by WangYng** [flutterchina/dio#1311]
### New Issue Checklist

- [x]  I have searched for a similar issue in the project and found none

### Issue Info

| Info                           | Value                                                 |    
| ------------------------------ | ----------------------------------------------------- |
| Platform Name                  |  flutter                        |    
| Platform Version               | 2.5.0                               |      
| Dio Version                    | 4.0.1                                  |      
| Android Studio  | Android Studio 2020.3.1             |      
|Repro rate | 100%|
|Demo project link| https://github.com/WangYng/dio_error |

### Issue Description and Steps

> flutter code

```dart
Future.microtask(() async {
  // save image to local path
  final bytes = Uint8List.view((await rootBundle.load("images/logo.png")).buffer);
  final file = File(path.join((await getTemporaryDirectory()).path, "logo.png"));
  if (!file.existsSync()) {
    await file.writeAsBytes(bytes);
  }

  // upload file to server
  final dio = Dio();
  dio.put("any url", data: File(file.path).readAsBytes().asStream());
});
```

> stack trace

``` 
[  +94 ms] E/flutter ( 1623): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: DioError [DioErrorType.other]: type '_StreamHandlerTransformer<List<int>, Uint8List>' is not a subtype of type 'StreamTransformer<Uint8List, Uint8List>' of 'streamTransformer'
[        ] E/flutter ( 1623): #0      Stream.transform (dart:async/stream.dart)
[        ] E/flutter ( 1623): #1      DioMixin._transformData (package:dio/src/dio_mixin.dart:734:18)
[        ] E/flutter ( 1623): #2      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:631:26)
[        ] E/flutter ( 1623): #3      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:585:7)
[        ] E/flutter ( 1623): #4      DioMixin.fetch._requestInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:502:28)
[        ] E/flutter ( 1623): #5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:797:22)
[        ] E/flutter ( 1623): #6      DioMixin.fetch._requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:500:22)
```

**Comment by wendux** [comment]
Firstly, I suggest to use `openRead` instead of `readAsBytes().asStream()`.
If you don't want to change your code, please upgrade dio to 4.0.3

**Comment by WangYng** [comment]
Thanks!
