### ISSUE TITLE
download empty content txt file(Size: 0 Byte) failed

### ISSUE THREAD

**Issue by nocsg** [flutterchina/dio#1358]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name               | e.g.     flutter                        |      |
| Platform Version            | e.g.   2.8.1                             |      |
| Dio Version                  | e.g.   4.0.4                          |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2              |      |
| Repro rate                  | e.g.    all the time (100%)    |      |
| Repro with our demo prj        | e.g. no            |      |
| Demo project link              | e.g. null |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
This is my code
the `remotePath` is point to a empty txt file in aws s3 bucket(Size: 0 Byte), my network is normal and I can download it in browser.
```
try {
      await dio!.download(
        remotePath!, 
        savePath,
        cancelToken: cancelToken,
        onReceiveProgress: (count , total) {
          onDownloadProgress!(count/total);
          if (count >= total) {
            L.d("Download Complete");
            if (onDownloadComplete != null) {
              onDownloadComplete!();
            }
          }
        }
      );
```
output log
```
E/TransportRuntime.CctTransportBackend( 8825): Couldn't encode request, returning with 400
E/TransportRuntime.CctTransportBackend( 8825): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/TransportRuntime.CctTransportBackend( 8825): 	at libcore.io.IoBridge.connect(IoBridge.java:135)
E/TransportRuntime.CctTransportBackend( 8825): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/TransportRuntime.CctTransportBackend( 8825): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/TransportRuntime.CctTransportBackend( 8825): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/TransportRuntime.CctTransportBackend( 8825): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/TransportRuntime.CctTransportBackend( 8825): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/TransportRuntime.CctTransportBackend( 8825): 	at java.net.Socket.connect(Socket.java:631)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:303)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.cct.CctTransportBackend.lambda$EzmIjpFiMjhFDTXmmEvw0ojyarw(Unknown Source:0)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.cct.-$$Lambda$CctTransportBackend$EzmIjpFiMjhFDTXmmEvw0ojyarw.apply(Unknown Source:4)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:154)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$Uploader(Uploader.java:103)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.-$$Lambda$Uploader$gD2ng4DJI1wrsPbN_hxDpvworD8.run(Unknown Source:8)
E/TransportRuntime.CctTransportBackend( 8825): 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
```

**Comment by jgoyvaerts** [comment]
If you google the error it suggests the server could be refusing the request (which is what 400 means, bad request) becaause of some authentication token issues (are you including or forgetting to include an authentication token?)

This doesn't seem like a dio problem.
