### ISSUE TITLE
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:

### ISSUE THREAD

**Issue by itcloudy** [flutterchina/dio#142]
我也出现了一样的问题，macpro android虚拟机

登录请求
```

Future<LoginToken> loginAccount(Map<String, String> params) async {
  BaseResponse<LoginToken> response =
      await HttpUtil().post<LoginToken>(ServerAPI.loginUrl, data: params);
  return response.data;
}
```
封装的请求
```
Future<BaseResponse<T>> post<T>(url, {data, options, cancelToken}) async {
    Response response;
    int _code;
    String _message;
    T _data;

    response = await _dio.post(
      url,
      data: data,
      cancelToken: cancelToken,
    );
    if (response.statusCode == HttpStatus.ok) {
      try {
        if (response.data is Map) {
          _message = response.data[_messageKey];
          _data = response.data[_dataKey];
          _code = (response.data[_codeKey] is String)
              ? int.tryParse(response.data[_codeKey])
              : response.data[_codeKey];
        } else {
          Map<String, dynamic> _dataMap = _decodeData(response);
          _code = (_dataMap[_codeKey] is String)
              ? int.tryParse(_dataMap[_codeKey])
              : _dataMap[_codeKey];
          _message = _dataMap[_messageKey];
          _data = _dataMap[_dataKey];
        }
        return BaseResponse(_code, _message, _data);
      } catch (e) {
        return new Future.error(new DioError(
          response: response,
          message: "data parsing exception...",
          type: DioErrorType.RESPONSE,
        ));
      }
    }
    return new Future.error(new DioError(
      response: response,
      message: "data parsing exception...",
      type: DioErrorType.RESPONSE,
    ));
  }

```
调用
```
Future<LoginToken> token = loginAccount(
                      {"username": _username, "password": _password});
                  print(token);
```
错误
```
I/flutter ( 8277): Instance of 'Future<LoginToken>'
E/flutter ( 8277): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 8277): NoSuchMethodError: The method 'post' was called on null.
E/flutter ( 8277): Receiver: null
E/flutter ( 8277): Tried calling: post<dynamic>("/login/account", cancelToken: null, data: _LinkedHashMap len:2)
E/flutter ( 8277): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 8277): #1      HttpUtil.post (package:flutter_erp/services/base.dart:59:27)
```

**Comment by wendux** [comment]
这是因为你的`_dio`变量不可用，它是在同一个文件内定义的吗？在其他文件创建的话看看是否映入成功，这个自己查一下吧，打印一下`print(_dio)`就知道了。
