### ISSUE TITLE
Dio download method throw 'Failed assertion: boolean expression must not be null' error

### ISSUE THREAD

**Issue by hirohe** [flutterchina/dio#207]
using Dio version 2.0.18

## Steps to Reproduce

```dart
var url = '<the download url which return 404>';
var filePath = '...';
var cancelToken = CancelToken();
await Dio().download(
  url,
  filePath,
  cancelToken: cancelToken,
).catchError((e) {
  print(e);
})
```
it will cause `Failed assertion: boolean expression must not be null` in catchError, is not real DioError

this code [L423](https://github.com/flutterchina/dio/blob/master/package_src/lib/src/dio.dart#L423) try to assert `options.receiveDataWhenStatusError`, but it is `null` actually

## Logs

```bash
#0      Dio.download (package:dio/src/dio.dart:423:21)
<asynchronous suspension>
#1      Updater.showUpgradeDialog.<anonymous closure>.<anonymous closure> (package:xxx/src/utils/updater.dart:150:33)
<asynchronous suspension>
#2      UpdateDialogState.build.<anonymous closure> (package:xxx/src/utils/updater.dart:289:22)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
#16     _rootRunUnary (dart:async/zone.dart:1136:13)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _invoke1 (dart:ui/hooks.dart:223:10)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by wendux** [comment]
fixed in v2.0.19
