### ISSUE TITLE
Get JSON response.data got error "NoSuchMethodError: The getter 'loader' was called on null.".

### ISSUE THREAD

**Issue by jaggerwang** [flutterchina/dio#28]
## Problem

Access `response.data` got error "NoSuchMethodError: The getter 'loader' was called on null.".

```
compiler message: Unhandled exception:
compiler message: NoSuchMethodError: The getter 'loader' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: loader
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:429)
compiler message: <asynchronous suspension>
compiler message: #2      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #3      new Future.sync (dart:async/future.dart:222)
compiler message: #4      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #5      _rootRun (dart:async/zone.dart:1126)
compiler message: #6      _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #7      _runZoned (dart:async/zone.dart:1518)
compiler message: #8      runZoned (dart:async/zone.dart:1465)
compiler message: #9      CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117)
compiler message: #10     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:428)
compiler message: <asynchronous suspension>
compiler message: #11     IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:103)
compiler message: #12     FrontendCompiler.compileExpression (package:vm/frontend_server.dart:448)
compiler message: <asynchronous suspension>
compiler message: #13     _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:55)
compiler message: #14     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:650)
compiler message: <asynchronous suspension>
compiler message: #15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
compiler message: #19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
compiler message: #20     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
compiler message: #21     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
compiler message: #22     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
compiler message: #23     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
compiler message: #24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
compiler message: #25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
compiler message: #29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
compiler message: #30     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
compiler message: #31     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
compiler message: #32     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
compiler message: #33     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
compiler message: #34     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
compiler message: #35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
compiler message: #36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #39     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
compiler message: #40     _StreamController._add (dart:async/stream_controller.dart:639)
compiler message: #41     _StreamController.add (dart:async/stream_controller.dart:585)
compiler message: #42     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
compiler message: #43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #46     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
compiler message: #47     _StreamController._add (dart:async/stream_controller.dart:639)
compiler message: #48     _StreamController.add (dart:async/stream_controller.dart:585)
compiler message: #49     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
compiler message: #50     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
compiler message: #51     _microtaskLoop (dart:async/schedule_microtask.dart:41)
compiler message: #52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
compiler message: #53     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
compiler message: #54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
Application finished.

```

## Code

```dart
import 'dart:io';
import 'dart:async';
import 'package:dio/dio.dart';
import 'package:logging/logging.dart';

import '../config.dart';
import '../factory.dart';

class TangboleService {
  final Logger logger;
  final Dio client;

  TangboleService()
      : this.logger = TangboleFactory().getLogger('service'),
        this.client = Dio() {
    this.client.options.baseUrl = TangboleConfig.tangboleApiBaseUrl;
    this.client.options.connectTimeout = 5000;
    this.client.options.receiveTimeout = 10000;

    if (TangboleConfig.isLogService) {
      this.client.interceptor.request.onSend = (Options options) {
        logger.fine(
            'TangboleService(method: ${options.method}, path: ${options.path}, data: ${options.data})');
        return options;
      };
      this.client.interceptor.response.onSuccess = (Response response) {
        logger.fine(
            'TangboleService(status: ${response.statusCode}, data: ${response.data})');
        return response;
      };
      this.client.interceptor.response.onError = (DioError e) {
        logger.fine('TangboleService(error: $e)');
        return e;
      };
    }
  }

  Future<TangboleApiResponse> request(String method, String path,
      {dynamic data, Duration timeout}) async {
    client.options.method = method;
    if (timeout != null) client.options.receiveTimeout = timeout.inMilliseconds;

    Response response;
    try {
      client.cookieJar = await TangboleFactory().getCookieJar();

      response =
          await client.request(path, data: data, options: client.options);
    } catch (e) {
      return TangboleApiResponse(
        code: TangboleApiResponseCode.request_timeout,
        message: e.toString(),
      );
    }

    if (response.statusCode == HttpStatus.ok) {
      return TangboleApiResponse.fromJson(response.data);
    } else {
      return TangboleApiResponse(
        code: TangboleApiResponseCode.response_status_not_ok,
        message: response.statusCode.toString(),
      );
    }
  }

class TangboleApiResponse {
  final int code;
  final String message;
  final dynamic data;

  TangboleApiResponse({
    this.code = TangboleApiResponseCode.ok,
    this.message = "",
    this.data,
  });

  TangboleApiResponse.fromJson(Map<String, dynamic> json)
      : this(
          code: json['code'] as int,
          message: json['message'] as String,
          data: json['data'],
        );

  Map<String, dynamic> toJson() => {
        'code': code,
        'message': message,
        'data': data,
      };

  @override
  String toString() => 'TangboleApiResponse${toJson()}';
}

class TangboleApiResponseCode {
  static const int ok = 0;
  static const int server_internal_error = -1;
  static const int request_timeout = -2;
  static const int response_status_not_ok = -3;
}

```

**Comment by wendux** [comment]
请定位到出错的代码行，整篇代码贴上来怎么看

**Comment by jaggerwang** [comment]
The reason is founded, I switched to beta (previous using dev) channel fixed this problem.

**Comment by wendux** [comment]
1.  首先你贴的代码里response.data有好几处，具体那一句不明确。
2.  任何issue都不会整篇代码往上贴，无论是国内还是国外，如果代码都是必要的，较长，都会在贴完代码后说明哪一行或那一句有问题(如果你上stackoverflow自己应该意识到)。这样可以节省看你issue人的时间。
3. 从栈中确实看不到dio内部代码报错信息。
4. 贴整篇代码总有把自己项目仍给其他人解决之嫌。
5. 本人只代表个人，即使本人态度不好，也无关国人，这对为开源社区做贡献的其他人不公平。本项目是为了共同学习，请勿在本项目下贴这种言论，谁都没有义务免费给别人写代码，大家做开源项目，本都是抱有分享之心，这样的言论不利于交流。
6. 如果我去一家店，我觉得服务态度不好，我完全可以扭头就走，再说，服务员只是多问了我一句有无忌口。
