### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OHeroJ** [flutterchina/dio#291]
```
Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, uri = xxxx

#0      Dio._makeRequest (package:dio/src/dio.dart:795:16)
<asynchronous suspension>
#1      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:707:22)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      _AsyncAwaitCompleter.co2019-05-10 13:48:23.745854+0800 SydneyToday[37697:7586154] 有网
mplete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
````

这种问题怎么解决

dio: 2.1.3

**Comment by MrChen2016-08-27** [comment]
请问解决了吗，我也遇到了这个问题

**Comment by yaochangliang159** [comment]
请问解决了吗，我也遇到了这个问题，我用的Dio 4.0.0
