### ISSUE TITLE
发送请求时携带类型为DateTime的参数报错。

### ISSUE THREAD

**Issue by leyan95** [flutterchina/dio#352]
你好：
       我在使用dio发送请求时遇到DateTime无法序列化的错误，请问有没有什么解决办法？

## 代码
```dart
Dio dio = new Dio();
dio.options.baseUrl = url;
dio.options.responseType = ResponseType.json;
Response<T> response = await dio.post<T>(url, data: Map.from({'a1': '001', 'a2': DateTime.now()}));
```

## 控制台错误信息
```
V/DartMessenger(31966): Received message from Dart over channel 'flutter/platform'
V/DartMessenger(31966): Deferring to registered handler to process message.
V/PlatformChannel(31966): Received 'SystemSound.play' message.
I/flutter (31966): DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'DateTime'
V/DartMessenger(31966): Received message from Dart over channel 'vibrate'
V/DartMessenger(31966): Deferring to registered handler to process message.
E/flutter (31966): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'DateTime'
E/flutter (31966): #0      Grab._dioPost.<anonymous closure> 
package:lsp_app/…/util/Grab.dart:98
E/flutter (31966): #1      _asyncErrorWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:84:45)
E/flutter (31966): #2      _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (31966): #3      _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (31966): #4      _FutureListener.handleError  (dart:async/future_impl.dart:140:20)
E/flutter (31966): #5      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:651:47)
E/flutter (31966): #6      Future._propagateToListeners  (dart:async/future_impl.dart:672:24)
E/flutter (31966): #7      Future._completeError  (dart:async/future_impl.dart:491:5)
E/flutter (31966): #8      _SyncCompleter._completeError  (dart:async/future_impl.dart:55:12)
E/flutter (31966): #9      _Completer.completeError  (dart:async/future_impl.dart:27:5)
E/flutter (31966): #10     _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (31966): #11     _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (31966): #12     _FutureListener.handleError  (dart:async/future_impl.dart:140:20)
E/flutter (31966): #13     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:651:47)
E/flutter (31966): #14     Future._propagateToListeners  (dart:async/future_impl.dart:672:24)
E/flutter (31966): #15     Future._completeError  (dart:async/future_impl.dart:491:5)
E/flutter (31966): #16     _SyncCompleter._completeError  (dart:async/future_impl.dart:55:12)
E/flutter (31966): #17     _Completer.completeError  (dart:async/future_impl.dart:27:5)
E/flutter (31966): #18     _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:40:18)
E/flutter (31966): #19     Dio._request (package:dio/src/dio.dart)
E/flutter (31966): #20     _asyncErrorWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:84:45)
E/flutter (31966): #21     _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (31966): #22     _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (31966): #23     _FutureListener.handleError  (dart:async/future_impl.dart:140:20)
E/flutter (31966): #24     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:651:47)
E/flutter (31966): #25     Future._propagateToListeners  (dart:async/future_impl.dart:672:24)
E/flutter (31966): #26     Future._completeError  (dart:async/future_impl.dart:491:5)
E/flutter (31966): #27     _SyncCompleter._completeError  (dart:async/future_impl.dart:55:12)
E/flutter (31966): #28     _Completer.completeError  (dart:async/future_impl.dart:27:5)
E/flutter (31966): #29     _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:40:18)
E/flutter (31966): #30     Dio._makeRequest (package:dio/src/dio.dart)
E/flutter (31966): #31     _asyncErrorWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:84:45)
E/flutter (31966): #32     _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (31966): #33     _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (31966): #34     _FutureListener.handleError  (dart:async/future_impl.dart:140:20)
E/flutter (31966): #35     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:651:47)
E/flutter (31966): #36     Future._propagateToListeners  (dart:async/future_impl.dart:672:24)
E/flutter (31966): #37     Future._completeError  (dart:async/future_impl.dart:491:5)
E/flutter (31966): #38     Future._asyncCompleteError.<anonymous closure>  (dart:async/future_impl.dart:539:7)
E/flutter (31966): #39     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (31966): #40     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (31966): #41     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter (31966): #42     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
E/flutter (31966): #43     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter (31966): #44     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
E/flutter (31966):
```

**Comment by wendux** [comment]
` DateTime.now().toString()`

**Comment by leyan95** [comment]
谢谢！
因为后台服务用的java 的 `LocalDateTime` 所以用 `toString()` 在反序列化时报错，后来用 `toIso8601String()` 搞定了
