### ISSUE TITLE
"type 'List<int>' is not a subtype of type 'Uint8List'"

### ISSUE THREAD

**Issue by breitembach** [flutterchina/dio#365]
### Issue Info
[](url)
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                          |      |
| Platform Version               | 1.5.4-hotfix.2                              |      |
| Dio Version                    | e.g.  ^2.1.10                                  |      |

### Issue Description and Steps
1 - FormData formData = FormData();
2 - formData.add("vehicles", List.from(["one", "two"]));

3 - Response response = await _dio.patch("/motorists/${UserSingleton.instance.user.id}", data: formData);

4 - throw a error:
"type 'List<int>' is not a subtype of type 'Uint8List'"

- dont accept Value as List

@wendux your last Merge  caused this problem?

**Comment by muyi0728** [comment]
I had the same problem as you.

**Comment by calvinmuller** [comment]
```
Unhandled Exception: DioError [DioErrorType.DEFAULT]: type 'List<int>' is not a subtype of type 'Uint8List'#0      Dio._transformData.<anonymous closure> (package:dio/src/dio.dart:853:20)
```

Same issue with 2.1.10

**Comment by biklas7** [comment]
I also have the same problem:

Output of `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.2 at /home/antonio/Documents/flutter
    • Framework revision 2e540931f7 (6 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/antonio/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/antonio/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/antonio/Documents/android-studio
    • Flutter plugin version 36.0.7
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.36.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
Output of `flutter run -v`:

```
[  +14 ms] I/flutter ( 6001): DioError [DioErrorType.DEFAULT]: type 'List<int>' is not a subtype of type 'Uint8List'#0      Dio._transformData.<anonymous closure>
(package:dio/src/dio.dart:853:20)
[   +1 ms] I/flutter ( 6001): #1      _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
[        ] I/flutter ( 6001): #2      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
[        ] I/flutter ( 6001): #3      _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] I/flutter ( 6001): #4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] I/flutter ( 6001): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[        ] I/flutter ( 6001): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[        ] I/flutter ( 6001): #7      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
[        ] I/flutter ( 6001): #8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
[        ] I/flutter ( 6001): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
[        ] I/flutter ( 6001): #10     _rootRun (dart:async/zone.dart:1120:38)
[        ] I/flutter ( 6001): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] I/flutter ( 6001): #12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[        ] I/flutter ( 6001): #13     _CustomZone.bindCallb
```

**Comment by biklas7** [comment]
@breitembach, @muyi0728 and @calvinmuller  I was able to solve my problem. The problem for me was converting a `List<Object>` to json.

I was doing:

```
  Map<String, dynamic> toJson() => {
        'id': id,
        'random_list': randomList,
      };
```

To solve the error I'm doing:

```
  Map<String, dynamic> toJson() => {
        'id': id,
        'random_list': json.encode(randomList),
      };
```

Hope that helps :smiley:

**Comment by haixiao2016** [comment]
use Dio Version  2.1.8 to fix them.

**Comment by biklas7** [comment]
But, won't this be fixed in future versions?
