### ISSUE TITLE
FileSystemException: Cannot open file, path = 'Instance of 'Future<File>'' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by SwissCheese5** [flutterchina/dio#431]
```
E/flutter (10583): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot open file, path = 'Instance of 'Future<File>'' (OS Error: Read-only file system, errno = 30)
E/flutter (10583): #0      _File.throwIfError (dart:io/file_impl.dart:643:7)
E/flutter (10583): #1      _File.openSync (dart:io/file_impl.dart:487:5)
E/flutter (10583): #2      Dio.download (package:dio/src/dio.dart:446:20)
E/flutter (10583): <asynchronous suspension>
E/flutter (10583): #3      Track.downloadThumbnail.<anonymous closure>.<anonymous closure> (package:chacha/music.dart:182:16)
E/flutter (10583): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (10583): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10583): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (10583): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (10583): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (10583): #9      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (10583): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (10583): #11     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (10583): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (10583): #13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (10583): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (10583): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10583): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10583): 
```

```dart
  Future<int> downloadThumbnail() {
    return getApplicationDocumentsDirectory().then((appDir) {
      File thumbFile = File(appDir.path + '/bin/thumbnails/$trackID.jpg');

      return thumbFile.exists().then((exists) {
        if (exists) {
          thumbnailFile = thumbFile;
          return 200;
        } else {
          return Dio()
              .download(thumbnailURL, File(appDir.path + '/bin/thumbnails/$trackID.jpg').create(recursive: true))
              .then((response) {
            if (response.statusCode == 200) {
              thumbnailFile = thumbFile;
            }

            return response.statusCode;
          });
        }
      });
    });
  }
```

**Comment by SwissCheese5** [comment]
Was passing a future instead of the file
