### ISSUE TITLE
logPrint( " " + null ) 报错

### ISSUE THREAD

**Issue by hurshi** [flutterchina/dio#471]
#### 报错位置
```
dio-3.0.1 -> lib -> src -> interceptors -> log.dart -> line: 106
```

#### 代码：

```
logPrint(" " + response?.headers?.toString()?.replaceAll("\n", "\n "));
```

#### 错误：

当 header 为 null 的时候，就变成 ` logPrint(" " + null)`， 进而报错：

```
2019-09-20 05:12:27.661 5710-5741/com.example.example I/flutter: DioError [DioErrorType.DEFAULT]: Invalid argument(s)
    #0      _StringBase.+ (dart:core-patch/string_patch.dart:263:57)
    #1      LogInterceptor._printResponse (package:dio/src/interceptors/log.dart:106:20)
    #2      LogInterceptor.onResponse (package:dio/src/interceptors/log.dart:95:5)
    <asynchronous suspension>
    #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
    #4      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1100:22)
    #5      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
    #6      new Future.<anonymous closure> (dart:async/future.dart:176:37)
    #7      _rootRun (dart:async/zone.dart:1120:38)
    #8      _CustomZone.run (dart:async/zone.dart:1021:19)
    #9      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
```

**Comment by wendux** [comment]
please update to 3.0.2-dev.1 and try again
