### ISSUE TITLE
连接超时的情况下 直接抛异常不好吧

### ISSUE THREAD

**Issue by zhanghaigang666** [flutterchina/dio#472]
连接超时的情况下，直接抛异常，调用者拿不到回调，这样处理不好吧
E/flutter (21154): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [10000ms]
E/flutter (21154): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:943:7)
E/flutter (21154): <asynchronous suspension>
E/flutter (21154): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
E/flutter (21154): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1100:22)
E/flutter (21154): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
E/flutter (21154): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter (21154): #5      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (21154): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21154): #7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (21154): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (21154): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (21154): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21154): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (21154): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (21154): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (21154): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (21154): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (21154):

**Comment by zhanghaigang666** [comment]
try可以捕获到，我的错，以为捕获不到，忘保存测试代码了
