### ISSUE TITLE
request error with path

### ISSUE THREAD

**Issue by CaiJingLong** [flutterchina/dio#6]
## StackTrace
----
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1#0      List.[] (dart:core/runtime/libgrowable_array.dart:141:60)
#1      Dio._makeRequest (package:dio/src/Dio.dart:341:30)
<asynchronous suspension>
#2      Dio._request.<anonymous closure> (package:dio/src/Dio.dart:320:16)
#3      Dio._checkIfNeedEnqueue (package:dio/src/Dio.dart:556:22)
#4      Dio._request (package:dio/src/Dio.dart:291:21)
<asynchronous suspension>
#5      Dio.request (package:dio/src/Dio.dart:274:12)
<asynchronous suspension>
#6      Dio.post (package:dio/src/Dio.dart:75:12)
#7      __LoginPageState&State&SizeUtils&HttpHelper.fetchWithDio (package:my_app/util/utils.dart:98:30)
<asynchronous suspension>
#8      _LoginPageState._login (package:my_app/pages/LoginPage.dart:366:32)
<asynchronous suspension>
#9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
#10     _InkResponseState.build.<anonymous <…>
```
---- 

## my code 
```
Dio dio = new Dio()
  ..options.baseUrl = new HttpUrl.get().host + "/"
  ..options.connectTimeout = 5000
  ..options.receiveTimeout = 5000;
```

```
var data = new FormData.from(params);
    data.add("a", httpUrl);
    data.add("m", url.m);
    var response = await dio.post("rest.php", data: data);
    return response.data;
```

## describe
My base url is `http://www.xxx.com/rest.php`.

Using the parameters of the form to distinguish the business logic.

If URL does not apply to restful, can you not use your plugin?

**Comment by CaiJingLong** [comment]
Thx, dart:io's HTTP does not need to start with http/https, I did not modify this part of the code in my code.

**Comment by TensaiZero** [comment]
I am having this issue as well.. Only occurs on dio.post... if I do a hot reload, without changing anything on the code the dio.post works. But if I restart the app using flutter run, the error occurs again.

**Comment by TensaiZero** [comment]
@wendux Got it  , just the base url. Thank you very much. Haven't initialized it on start.
