### ISSUE TITLE
dio mac support?

### ISSUE THREAD

**Issue by softmarshmallow** [flutterchina/dio#725]
android, web, ios with dio worked fine, but with mac,..
i see below message

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = XXXX, port = XXX
#0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
<asynchronous suspension>
#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#5      _rootRun (dart:async/zone.dart:1129:38)
#6      _CustomZone.run (dart:async/zone.dart:1026:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:928:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:23)
#9      _rootRun (dart:async/zone.dart:1133:13)
#10     _CustomZone.run (dart:async/zone.dart:1026:19)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:952:23)
#12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by huntergps** [comment]
To activate network connection in macOS, add the following lines to your macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>

**Comment by ZeroJsus** [comment]
> To activate network connection in macOS, add the following lines to your macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements com.apple.security.network.server com.apple.security.network.client

after set the key is true. you need to rebuild your app also.
