### ISSUE TITLE
Why Does This Request Fail With Error: RangeError (index0: invalid value: Valid value range is empty?

### ISSUE THREAD

**Issue by eopeter** [flutterchina/dio#77]
Error: flutter: DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Valid value range is empty: 0#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:234:55)
#1      _Cookie._validate (dart:_http/http_headers.dart:989:14)
#2      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:933:5)
-----

Server returns JSON matching MessageResponse
------------

Future<MessageResponse> getMessages(int clientId, int pageNumber) async {
    MessageResponse messageResponse = new MessageResponse();

    try {
      Response<MessageResponse> result =
          await client.get('$baseRoute/clients/$clientId/messages/$pageNumber');
      if (result.statusCode == HttpStatus.ok) {

        messageResponse = result.data;

      }
    }catch(exception){print(exception);}
      return messageResponse;
    }

Object Is:
---------

@JsonSerializable()
class MessageResponse
{
  int page = 0;
  int totalItems = 0;
  int itemsPerPage = 0;
  List<ChatMessage> messages = new List<ChatMessage>();

  MessageResponse();

  factory MessageResponse.fromJson(Map<String, dynamic> json) => _$MessageResponseFromJson(json);
   Map<String, dynamic> toJson() => _$MessageResponseToJson(this);

}

@JsonSerializable()
class ChatMessage
{
  int id;
  int senderId;
  String senderName;
  String senderPhotoUrl;
  String imageUrl;
  String text;
  DateTime timeStamp;
  bool isNew;
  String timeStampString;
  bool hideSender = false;
  bool showTimeStamp = true;
  ChatMessage();

  factory ChatMessage.fromJson(Map<String, dynamic> json) => _$ChatMessageFromJson(json);
   Map<String, dynamic> toJson() => _$ChatMessageToJson(this);

}

JSON Is
---------
{
    "page": 0,
    "itemsPerPage": 20,
    "totalItems": 2,
    "messages": [
        {
            "id": 218,
            "senderId": 250,
            "senderName": "Mobile App",
            "senderPhotoUrl": "https://gog.ws/FrontEnd/images/icons/avatar.jpg",
            "imageUrl": "null",
            "text": "this is a test",
            "timeStamp": "2018-09-30T03:19:41.3393623",
            "isNew": false,
            "timeStampString": "yesterday"
        },
        {
            "id": 208,
            "senderId": 609,
            "senderName": "Drew Pats",
            "senderPhotoUrl": "https://gog.ws/images/icons/avatar.jpg",
            "imageUrl": null,
            "text": "Can I reschedule?",
            "timeStamp": "2018-09-28T17:46:28.519898",
            "isNew": false,
            "timeStampString": "3 days ago"
        }
}

**Comment by wendux** [comment]
Response<T> "T" must be one of `Map`、`List`、`String` 、`HttpClientResponse`,  Which one ultimately depends on `Options.responseType`:

![image](https://user-images.githubusercontent.com/20411648/46711460-fdc08b80-cc7e-11e8-81cb-4bb2a1c8c424.png)

| T                  | responseType        |
| ------------------ | ------------------- |
| Map、List          | ResponseType.JSON   |
| String             | ResponseType.PLAIN  |
| HttpClientResponse | ResponseType.STREAM |
