### ISSUE TITLE
with Valid Token but Still Always Getting 401 unauthorised Response  

### ISSUE THREAD

**Issue by saikrishna7789** [flutterchina/dio#787]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter                         |      |
| Dio Version                    | e.g.  any                                |      |
| Android Studio | e.g. Android Studio 3.6.1           |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**IN PostMan And In Android Studio Using Java Also Fine Only in Flutter Dio Getting Unauthoried**

Code : 
```

  Dio getDio(){

    Dio dio = new Dio(new BaseOptions(
      baseUrl: Constants.HostUrl,
    ));
    dio.interceptors.addAll([
      InterceptorsWrapper(onRequest: (RequestOptions options)  {
        var token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.";
        var customHeaders = {
          "content-type" : 'application/json',
          'apikey': '12345678',
          'Authorization': 'Bearer $token'
        };
        print(customHeaders.values);
        options.headers.addAll(customHeaders);
        return options;
      }),
      LogInterceptor(
        requestBody: true,
        responseBody: true,
      ),
    ]
    );
    return dio;
  }


```

call:
```

getDio().post(Constants.resetPassword,data: {
            "password": 'password',
            "password_confirmation": 'password'
          });
```

Request Log
```


 *** Request ***
I/flutter ( 4525): uri: http://xxxxxxxxxxxxxxxxxxxxxxxx
I/flutter ( 4525): method: POST
I/flutter ( 4525): responseType: ResponseType.json
I/flutter ( 4525): followRedirects: true
I/flutter ( 4525): connectTimeout: 0
I/flutter ( 4525): receiveTimeout: 0
I/flutter ( 4525): extra: {}
I/flutter ( 4525): headers:
I/flutter ( 4525):  content-type: application/json
I/flutter ( 4525):  apikey: 12345678
I/flutter ( 4525):  Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.
I/flutter ( 4525): data:
I/flutter ( 4525): {password: password, password_confirmation: password}
I/flutter ( 4525): 


```

Response Log

```

*** DioError ***:
I/flutter ( 4525): uri: http://xxxxxxxxxxxxxx
I/flutter ( 4525): DioError [DioErrorType.RESPONSE]: Http status error [401]
I/flutter ( 4525): uri: http://xxxxxxxxxxxxxxx
I/flutter ( 4525): statusCode: 401
I/flutter ( 4525): headers:
I/flutter ( 4525):  content-type: application/json; charset=utf-8
I/flutter ( 4525):  date: Fri, 15 May 2020 07:47:13 GMT
I/flutter ( 4525):  content-length: 14
I/flutter ( 4525):  server: Apache/2.4.29 (Ubuntu)
I/flutter ( 4525): Response Text:
I/flutter ( 4525): Unauthorised
I/flutter ( 4525): 
I/flutter ( 4525): 
E/flutter ( 4525): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [401]
E/flutter ( 4525): #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart:869:13)
E/flutter ( 4525): <asynchronous suspension>
E/flutter ( 4525): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 4525): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 4525): #3      _FutureListener.handleError (dart:async/future_impl.dart:158:20)
E/flutter ( 4525): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter ( 4525): #5      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter ( 4525): #6      Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 4525): #7      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 4525): #8      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart)
E/flutter ( 4525): <asynchronous suspension>
E/flutter ( 4525): #9      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 4525): #10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 4525): #11     _FutureListener.handleError (dart:async/future_impl.dart:158:20)
E/flutter ( 4525): #12     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter ( 4525): #13     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter ( 4525): #14     Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 4525): #15     _SyncCompleter._completeError (dart:async/future_impl.dart:57:12)
E/flutter ( 4525): #16     _Completer.completeError (dart:async/future_impl.dart:29:5)
E/flutter ( 4525): #17     Future.any.<anonymous closure> (dart:async/future.dart:462:45)
E/flutter ( 4525): #18     _rootRunBinary (dart:async/zone.dart:1146:38)
E/flutter ( 4525): #19     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
E/flutter ( 4525): #20     _FutureListener.handleError (dart:async/future_impl.dart:154:20)
E/flutter ( 4525): #21     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter ( 4525): #22     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter ( 4525): #23     Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 4525): #24     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 4525): #25     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter ( 4525): <asynchronous suspension>
E/flutter ( 4525): #26     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter ( 4525): #27     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
E/flutter ( 4525): #28     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter ( 4525): #29     new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 4525): #30     _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 4525): #31     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4525): #32     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 4525): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 4525): #34     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 4525): #35     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4525): #36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter ( 4525): #37     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 4525): #38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 4525): #39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 4525): #40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 4525): 

```

**Comment by sohampandyaserpro** [comment]
+1

**Comment by matejthetree** [comment]
how did you resolve this?
