### ISSUE TITLE
Flutter混编iOS的时候dio请求会超时

### ISSUE THREAD

**Issue by cxycwz** [flutterchina/dio#882]
服务器这边返回正常的，原生框架去请求同一个接口，每次都会成功，使用flutter部分调用dio去请求则会出现timeout，10次请求，会有一两次timeout。针对iOS会有额外的dio配置方案吗？协议为https，但为忽略证书验证的

**Comment by cxycwz** [comment]
我在网络上也搜到了类似的问题，https://gitmemory.com/issue/flutterchina/dio/349/506129938，目前还没找到相应的解决方案

**Comment by cxycwz** [comment]
报超时的时候，栈错误

```shell
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
│ \^[[0m\^[[39m\^[[48;5;196mDioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [10000ms]<…>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
│ #0   Http._interceptorConf.() (package:carmodule/common/network/http.dart:106:9<…>
│ #1   InterceptorsWrapper.onError (package:dio/src/interceptor.dart:125:2<…>
│ #2   DioMixin._request._errorInterceptorWrapper.() (package:dio/src/dio.dart:867:4<…>
│ #3   _rootRunUnary (dart:async/zone.dart:1192:3<…>
│ #4   _CustomZone.runUnary (dart:async/zone.dart:1085:1<…>
│ #5   _FutureListener.handleError (dart:async/future_impl.dart:159:2<…>
│ #6   Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:4<…>
│ #7   Future._propagateToListeners (dart:async/future_impl.dart:715:2<…>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
│ ⛔ msg:Connecting timed out [10000ms], api: /order/payType<…>
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
```

**Comment by peterlpt** [comment]
mark，遇到同样的问题

**Comment by heimabailang** [comment]
mark，遇到同样的问题

**Comment by heimabailang** [comment]
mark，遇到同样的问题

**Comment by heimabailang** [comment]
mark，遇到同样的问题

**Comment by icespring** [comment]
same issue

**Comment by nEdAy** [comment]
same issue
