### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException

### ISSUE THREAD

**Issue by jyotirmoy-paul** [flutterchina/dio#884]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                          |      |
| Platform Version               | API 29                              |      |
| Dio Version                    | 3.0.9                                  |      |
| Android Studio Version |  Android Studio 3.6.3              |      |
| Repro rate                     | all the time (100%)    |      |
| Repro with our demo prj        | yes           |      |

### Issue Description and Steps

A post request to this URL: "https://test.saferpay.com/api/payment/v1/paymentpage/initialize" causes an exception. whereas the same URL works in Postman and Curl. Most likely this is a problem with HttpClient, please point me to the right direction.

Here is the full code:
```void send() async {
    Dio dio = Dio();

    final Map<String, String> _headers = {
      HttpHeaders.contentTypeHeader: "application/json; charset=utf-8",
      HttpHeaders.acceptHeader: "application/json",
      HttpHeaders.authorizationHeader:
          "Basic AUTH-GOES-HERE",
    };
    var response = await dio.post(
      "https://test.saferpay.com/api/payment/v1/paymentpage/initialize",
      options: Options(headers: _headers),
      data: {
        "RequestHeader": {
          "SpecVersion": "1.2",
          "CustomerId": "XXXXX",
          "RequestId": "this0is0a0random2request9id",
          "RetryIndicator": 0
        },
        "TerminalId": "17726017",
        "Payment": {
          "Amount": {"Value": 259000, "CurrencyCode": "CHF"},
          "OrderId": "this3is3another2order1id9for4this0is0a0random2request9id",
          "Description": "Payment"
        },
        "ReturnUrls": {
          "Success":
              "some.domain.com/payment_response\/success.html",
          "Fail":
              "another.domain.com/payment_response\/false.html"
        }
      },
    );

    print(response.data);
  }
```

## I am getting the following exception:

```E/flutter (25173): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: , uri = https://test.saferpay.com/api/payment/v1/paymentpage/initialize
E/flutter (25173): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
E/flutter (25173): <asynchronous suspension>
E/flutter (25173): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter (25173): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
E/flutter (25173): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter (25173): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter (25173): #5      _rootRun (dart:async/zone.dart:1180:38)
E/flutter (25173): #6      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (25173): #7      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (25173): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (25173): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (25173): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (25173): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (25173): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (25173): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (25173): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (25173): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (25173): 
```

**Comment by HyBLF** [comment]
请问解决了吗？遇到同样的问题

**Comment by NRMrYang** [comment]
I also encountered this problem. Who can give some advice

**Comment by javdev** [comment]
same problem here, no solution

**Comment by javdev** [comment]
got a solution, that worked for me: I deleted the emulators and then created new emulators. Then it worked again.

**Comment by Lawati97** [comment]
I keep on getting the same issue but when I recall the API it works smoothly
