### ISSUE TITLE
option中设置responseType为ResponseType.plain时接收服务端响应的字符串仍然会报错

### ISSUE THREAD

**Issue by leyan95** [flutterchina/dio#885]
- 后台接口
```java
@RequestMapping(actionId = "status")
public String status() {
     return "p4l5SZOiR/LbLS7ln7d7BkWjmtqNIN1zctyFcSKCgsM//K1DjcgMWKKNl6jkMopF0tcVpgAZdTM=";
 }
```

- 客户端
```dart
  final Dio _dio = new Dio(BaseOptions(
    connectTimeout: buck.cacheControl.connectTimeout ?? 10000,
    receiveTimeout: buck.cacheControl.receiveTimeout ?? 40000,
    responseType: ResponseType.plain,
  ));
```

- 异常信息
```
E/flutter (22014): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: , uri = http://222.223.3.133:62980/Rfid/RestService.asmx/MBS_BloodStorageAndTransport/BSTHttpHandler/Status
E/flutter (22014): #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart:869:13)
E/flutter (22014): <asynchronous suspension>
E/flutter (22014): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (22014): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (22014): #3      _FutureListener.handleError (dart:async/future_impl.dart:158:20)
E/flutter (22014): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter (22014): #5      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter (22014): #6      Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter (22014): #7      _SyncCompleter._completeError (dart:async/future_impl.dart:57:12)
E/flutter (22014): #8      _Completer.completeError (dart:async/future_impl.dart:29:5)
E/flutter (22014): #9      Future.any.<anonymous closure> (dart:async/future.dart:462:45)
E/flutter (22014): #10     _rootRunBinary (dart:async/zone.dart:1146:38)
E/flutter (22014): #11     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
E/flutter (22014): #12     _FutureListener.handleError (dart:async/future_impl.dart:154:20)
E/flutter (22014): #13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter (22014): #14     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter (22014): #15     Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter (22014): #16     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:15)
E/flutter (22014): #17     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter (22014): <asynchronous suspension>
E/flutter (22014): #18     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter (22014): #19     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
E/flutter (22014): #20     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter (22014): #21     new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter (22014): #22     _rootRun (dart:async/zone.dart:1122:38)
E/flutter (22014): #23     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (22014): #24     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (22014): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (22014): #26     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (22014): #27     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (22014): #28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (22014): #29     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (22014): #30     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (22014): #31     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (22014): #32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by dingshaohua-com** [comment]
俺也一样。无论怎么搞都一直报错
```
 var options = Options(
      method: 'GET',
      responseType: ResponseType.plain); // 设置为 plain，避免自动解析
  var params = getSongsParams();
  const url = 'https://u.y.qq.com/cgi-bin/musicu.fcg';
  var result = {};
  try {
    final res = await dio.get(url, queryParameters: params, options: options);
  } catch (e) {
  }
```

```
🔔 Dio] Failed to parse the media type: text/plain; charset=utf-8;, thus it is not a JSON MIME type.
         #0      wrapFormatException (package:http_parser/src/utils.dart:15:5)
         #1      new MediaType.parse (package:http_parser/src/media_type.dart:46:7)
         #2      Transformer.isJsonMimeType (package:dio/src/transformer.dart:82:35)
         #3      FusedTransformer.transformResponse (package:dio/src/transformers/fused_transformer.dart:61:39)
         #4      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:559:42)
         <asynchronous suspension>
         #5      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:483:25)
         <asynchronous suspension>
```
