### ISSUE TITLE
响应码302，但没有 redirect 信息，打印 redirect 信息出现异常 

### ISSUE THREAD

**Issue by wanderingGuy** [flutterchina/dio#902]
```
I/flutter (24675): DioError [DioErrorType.DEFAULT]: Bad state: No element
I/flutter (24675): #0      List.last (dart:core-patch/growable_array.dart:227:5)
I/flutter (24675): #1      Response.realUri (package:dio/src/response.dart:56:32)
I/flutter (24675): #2      LogInterceptor._printResponse (package:dio/src/interceptors/log.dart:101:39)
I/flutter (24675): #3      LogInterceptor.onResponse (package:dio/src/interceptors/log.dart:93:5)
I/flutter (24675): #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
I/flutter (24675): #5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
I/flutter (24675): #6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
I/flutter (24675): #7      new Future.<anonymous closure> (dart:async/future.dart:176:37)
I/flutter (24675): #8      _rootRun (dart:async/zone.dart:1122:38)
I/flutter (24675): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (24675): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
I/flutter (24675): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
I/flutter (24675): #12     _rootRun (dart:a
```
.last函数抛出异常，应添加判断
```
class Response {
  ...
  /// Return the final real request uri (maybe redirect).
  ///
  /// ** Attention **: Whether this field is available depends on whether the
  /// implementation of the adapter supports it or not.
  Uri get realUri => redirects.last?.location ?? request.uri;

```

**Comment by dpossas** [comment]
I have the same problem happening in my application

**Comment by easazade** [comment]
you're problem could be solved by creating a new `Dio` instance for that request. apparently when you set `followRedirect` to false for a specific request it doesn't work on the `dio` instance that had its `followRedirects` to true. so you have to create a new dio instance.

**Comment by jiashaoying** [comment]
使用dio.request
