### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101)

### ISSUE THREAD

**Issue by maninwindow** [flutterchina/dio#941]
### The Flutter Widget

```
Widget _sendSMSMessage(String text) {
    final URI =
        Constants.of().endpoint + '/api/users?phonenumber=' + _phonenumber;
    Future<String> sendSMSMessage() async {
      await dio.get<String>(URI).then((response) {
        setState(() {
          smsCodeReceived = response.data.toString();
        });
      });
    }

    return RaisedButton(
      child: Text(smsPressed ? 'Resend after ' + _start.toString() : text),
      onPressed: () {
        sendSMSMessage();
        setState(() {
          sendSMSM();
        });
      },
      color: Theme.of(context).primaryColor,
      elevation: 5,
      textColor: Colors.white,
    );
  }
```

### Error Message

```
V/AudioManager(20417): playSoundEffect   effectType: 0
V/AudioManager(20417): querySoundEffectsEnabled...
E/flutter (20417): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = {MY_LOCAL_IP_ADDRESS}, port = 5000
E/flutter (20417): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:966:7)
E/flutter (20417): <asynchronous suspension>
E/flutter (20417): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter (20417): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
E/flutter (20417): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter (20417): #4      new Future.<anonymous closure> (dart:async/future.dart:175:37)
E/flutter (20417): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (20417): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20417): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (20417): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (20417): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (20417): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20417): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (20417): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (20417): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (20417): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (20417): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

API works fine with Postman. I have no idea what is the reason of this issue? Anybody does?

**Comment by ShahzadUmarBaig** [comment]
Faced something similar in Release version of the app, Dio was failing to upload images. Although I found a solution that worked for me. 

Add this permission 

<uses-permission android:name="android.permission.INTERNET" />

to your app level Manifest.

 android/app/src/main/AndroidManifest.xml

Solution can be found here

https://stackoverflow.com/a/59392036/14641365
